export type AssessmentType = "written_work" | "performance_task" | "quarterly_assessment";

export interface AssessmentProps {
    id: number,
    classSubjectId: number,
    quarter: number,
    type: AssessmentType,
    title: string,
    maxScore: number,
    dateGiven: string | null
    created_at: string;
}

// Payload needed to create a new assessment (id is auto-generated by the DB).
export interface AssessmentCreateProps {
    classSubjectId: number;
    quarter: number;
    type: AssessmentType;
    title: string;
    maxScore: number;
    dateGiven?: string | null;
}

// Fields a teacher is allowed to edit on an existing assessment.
export interface AssessmentUpdateProps {
    title?: string;
    type?: AssessmentType;
    maxScore?: number;
    dateGiven?: string | null;
}